{
	"version": 1576204607,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/spritefont.png",
		"images/startandoptionwtf.png",
		"images/sprite6-sheet0.png",
		"images/menubackground-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/selection-sheet0.png",
		"images/menubouncer1-sheet0.png",
		"images/bgplanet2-sheet0.png",
		"images/bgplanets2-sheet0.png",
		"images/bgsaturn2-sheet0.png",
		"images/bgstars2-sheet0.png",
		"images/background-sheet0.png",
		"images/backgroundbouncer-sheet0.png",
		"images/backgroundbouncer1-sheet0.png",
		"images/godmodebox-sheet0.png",
		"images/hpdisplay-sheet0.png",
		"images/pixelarrowkey-sheet0.png",
		"images/pixelspacebar-sheet0.png",
		"images/planedisplay-sheet0.png",
		"images/bossreaper-sheet0.png",
		"images/bossreapersphere-sheet0.png",
		"images/bossreaperhp-sheet0.png",
		"images/bigball-sheet0.png",
		"images/bossreaperdeathsphere-sheet0.png",
		"images/bosseye-sheet0.png",
		"images/bosseye-sheet1.png",
		"images/bosssphere-sheet0.png",
		"images/enemybullet-sheet0.png",
		"images/enemybulletminus90-sheet0.png",
		"images/bullet-sheet0.png",
		"images/hp1-sheet0.png",
		"images/hp-sheet0.png",
		"images/enemy-sheet0.png",
		"images/bullet2-sheet0.png",
		"images/particles.png",
		"images/particles2.png",
		"images/sprite3-sheet0.png",
		"images/tiledbackground.png",
		"media/bossphotonbeam.m4a",
		"media/bossphotonbeam.ogg",
		"media/bosssound.m4a",
		"media/bosssound.ogg",
		"media/bossdeathexplosion.m4a",
		"media/bossdeathexplosion.ogg",
		"media/bosstriplebullet.m4a",
		"media/bosstriplebullet.ogg",
		"media/selectsound.m4a",
		"media/selectsound.ogg",
		"media/selectconfirm.m4a",
		"media/selectconfirm.ogg",
		"media/se_00000.m4a",
		"media/se_00000.ogg",
		"media/se_00028.m4a",
		"media/se_00028.ogg",
		"media/shoot.m4a",
		"media/shoot.ogg",
		"media/playeronhitsound.m4a",
		"media/playeronhitsound.ogg",
		"media/march of the white knights.m4a",
		"media/march of the white knights.ogg",
		"media/all systems, go.m4a",
		"media/all systems, go.ogg",
		"media/hopes and dreams (va-11 hall-a).m4a",
		"media/hopes and dreams (va-11 hall-a).ogg",
		"media/youve got me (va-11 hall-a).m4a",
		"media/youve got me (va-11 hall-a).ogg",
		"media/those who dwell in the shadows (va-11 hall-a).m4a",
		"media/those who dwell in the shadows (va-11 hall-a).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}